---
title: "A Multilevel Modeling for Single-Case Data Across Research Designs: Math Acquisition, Maintenance, and Generalization"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    theme: flatly
    code_folding: hide
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  message = FALSE, 
  warning = FALSE
)
```

This is an online supplemental materials for Authors (2022) to visualize single-case data. The entire R codes for data analysis is available in the [Open Science Framework](https://osf.io/dashboard) platform. 

## {.tabset}

### Select the dataset
```{r}
suppressPackageStartupMessages({
  library(readxl)
  library(openxlsx)
  library(DT)
  library(shiny)
  library(shinyBS)
  library(dplyr)
  library(ggplot2)
  library(plotly)
})

wp_data <- read_excel("wp_data_list_c.xlsx")

observe({
  updateRadioButtons(session, "show_vars",
                     label = NULL,
                     choices = colnames, 
                     selected = "")
})

colnames <- (unique(wp_data$author_year))

inputPanel(
  radioButtons("show_vars", "Select one or multiple columns.",
               choices = colnames)
)
```

```{r, echo = FALSE}
br()
br()
br()
```


### Datasets
```{r, echo=FALSE}
inputPanel(
  actionButton("display", "Display", icon = icon("table")),
  downloadButton("download_table", "Download")
)
```

```{r}
wp_data_select <- eventReactive(input$display, {
  
  if (!is.null(input$show_vars)) {
    wp_data %>% filter(author_year == input$show_vars) %>% tibble()
  }
})

renderDataTable(wp_data_select())
```


```{r, echo=FALSE}
output$download_table <- downloadHandler(
  filename = function() {
    paste(input$show_vars, ".xlsx", sep = "")
  },
  content = function(file) {
    write.xlsx(wp_data_select(), file, colNames = TRUE)
  }
)
```


```{r, echo=FALSE}
br()
```


### Plot
```{r, echo=FALSE}
inputPanel(
  actionButton("plot", "Plot", icon = icon("play"))
)
```


```{r}
observeEvent(input$plot, {
  
    wp_data_select_td <- wp_data_select()
    
    wp_data_select_td$case <- paste0("Case ", wp_data_select_td$case, sep = "")
    wp_data_select_td$group <- paste0("Group ", wp_data_select_td$group, sep = "")
    wp_data_select_td$cluster <- paste0("Cluster ", wp_data_select_td$cluster, sep = "")
    wp_data_select_td$study <- paste0("Study ", wp_data_select_td$study, sep = "")
  

    B1_v <- if(!is.null(wp_data_select_td$B1)) {
      wp_data_select_td %>%
        filter(B1 == 1) %>%
        group_by(cluster, group, case) %>%
        mutate(max_B1 = max(session))
    }

    T1_v <- if(!is.null(wp_data_select_td$T1)) {
      wp_data_select_td %>%
        filter(T1 == 1) %>%
        group_by(cluster, group, case) %>%
        mutate(max_T1 = max(session))
    }

    B2_v <- if(!is.null(wp_data_select_td$B2)) {
      wp_data_select_td %>%
        filter(B2 == 1) %>%
        group_by(cluster, group, case) %>%
        mutate(max_B2 = max(session))
    }

    T2_v <- if(!is.null(wp_data_select_td$T2)) {
      wp_data_select_td %>%
        filter(T2 == 1) %>%
        group_by(cluster, group, case) %>%
        mutate(max_T2 = max(session))
    }

    T3_v <- if(!is.null(wp_data_select_td$T3)) {
      wp_data_select_td %>%
        filter(T3 == 1) %>%
        group_by(cluster, group, case) %>%
        mutate(max_T3 = max(session))
    }

    T4_v <- if(!is.null(wp_data_select_td$T4)) {
      wp_data_select_td %>%
        filter(T4 == 1) %>%
        group_by(cluster, group, case) %>%
        mutate(max_T4 = max(session))
    }

    P_v <- if(!is.null(wp_data_select_td$P)) {
      wp_data_select_td %>%
        filter(P == 1) %>%
        group_by(cluster, group, case) %>%
        mutate(max_P = max(session))
    }

    M1_v <- if(!is.null(wp_data_select_td$M1)) {
      wp_data_select_td %>%
        filter(M1 == 1) %>%
        group_by(cluster, group, case) %>%
        mutate(max_M1 = max(session))
    }

    G1_v <- if(!is.null(wp_data_select_td$G1)) {
      wp_data_select_td %>%
        filter(G1 == 1) %>%
        group_by(cluster, group, case) %>%
        mutate(max_G1 = max(session))
    }
    
    output$pl <- renderPlot({
      
      req(input$plot)
      
      sced.plot <- wp_data_select_td %>%
        ggplot(aes(session, outcome, color = as.factor(phase), shape = phase)) +
        facet_grid(cluster + group + case ~ .) +
        geom_line(data = wp_data_select_td %>% filter(phase %in% c("Baseline 1", "Intervention 1", "Baseline 2", "Intervention 2", "Intervention 3", "Intervention 4", "Probe", "Maintenance", "Generalization")),
                  aes(group = phase),
                  position = position_dodge(width = 0.3),
                  size = 0.3) +
        geom_point(size = 1.7) +
        theme_minimal(base_size = 13) +
        theme(
          plot.title = element_text(face = "bold", size = 15),
          legend.position ="top",
          panel.grid.major = element_line(colour = "grey90", size = 0.2),
          panel.grid.minor = element_blank(),
          legend.text = element_text(size = 13),
          legend.title = element_text(size = 13),
          legend.title.align = 0.5,
          strip.text.y = element_text(color = "#3B3B3B", size = 13),
          axis.text.x = element_text(size = 13, color = "#3B3B3B"),
          axis.text.y = element_text(size = 13, color = "#3B3B3B"),
          axis.title = element_text(face = "bold", size = 13, color = "#3B3B3B")
        ) +
        labs(
          x = "Session",
          y = "Correct Percentage",
          title = input$show_vars
        ) +
        guides(shape="none") +
        guides(color = guide_legend(title = "Phase"), shape = guide_legend(title="Phase")) +
        scale_shape_manual(values = 0:10) +
        geom_vline(data = B1_v, ggplot2::aes(xintercept = B1_v$max_B1 + 0.5),
                   linetype = "dashed", size = 0.3) +
        geom_vline(data = T1_v, ggplot2::aes(xintercept = T1_v$max_T1 + 0.5),
                   linetype = "dashed", size = 0.3) +
        geom_vline(data = B2_v, ggplot2::aes(xintercept = B2_v$max_B2 + 0.5),
                   linetype = "dashed", size = 0.3) +
        geom_vline(data = T2_v, ggplot2::aes(xintercept = T2_v$max_T2 + 0.5),
                   linetype = "dashed", size = 0.3) +
        geom_vline(data = T3_v, ggplot2::aes(xintercept = T3_v$max_T3 + 0.5),
                   linetype = "dashed", size = 0.3) +
        geom_vline(data = T4_v, ggplot2::aes(xintercept = T4_v$max_T4 + 0.5),
                   linetype = "dashed", size = 0.3) +
        # geom_vline(data = P_v, ggplot2::aes(xintercept = P_v$max_P + 0.5),
                   # linetype = "dashed", size = 0.3) +
        geom_vline(data = M1_v, ggplot2::aes(xintercept = M1_v$max_M1 + 0.5),
                   linetype = "dashed", size = 0.3) 
        # geom_vline(data = G1_v, ggplot2::aes(xintercept = G1_v$max_G1 + 0.5),
                   # linetype = "dashed", size = 0.3)
      
      sced.plot
      
    })
    
})

bsCollapse(id="asdf", open=0,
           bsCollapsePanel("Click to set plot dimensions", value=1, style="success",
                           p(strong("Dimensions of the plot")),
                           div(style="display:inline-block", sliderInput(inputId = "height", post=" px",
                                                                         label = "height", min = 500, max = 4000, step = 5, value = 2000)),
                           div(style="display:inline-block", sliderInput(inputId = "width", post=" px",
                                                                         label = "width",  min = 500, max = 1000, step = 5, value = 900))
           )
)

renderUI({
  plotOutput("pl", height=input$height, width=input$width)
})
```






